name: Build Full Docker Container

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: full/1.0.0
          file: full/1.0.0/Dockerfile
          push: false
          tags: schillerlab/sc-container:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}