name: Publish Github container

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          username: zethson
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: base
          registry: ghcr.io
          tags: latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}